#!/bin/sh
# .:[ rawk - rage against web frameworks ]:.
# 
# generates a static content from a tree of markdown files and other content
# originally written by 4096R/B7B720D6  "Kyle Isom <coder@kyleisom.net>"
# based on the suckless webframework (sw) by nibblesec
# 
# released as public domain software - for curiosity's sake, i'd be interested in hearing
# if you take this and tinker with it, though you are far from obligated to do so.

CONF_FILE="rawkrc"
SRC_DIR="$1"


usage () {
    echo "usage: $0 <source dir>"
    exit 0
}

build_header () {

    print $(cat ${HDR_TPL} | sed -e 's/\$\{TITLE\}/$SITE_TITLE/ ; 
                                     s/\$\{SUBTITLE\}/$SITE_SUBTITLE')
}

build_submenu () {
    FC=""               # filter chain
    FILE_LIST=""
    print "<div id=\"side-bar\">"

    for filter in $BL
    do
        FC="$FC | grep -v '$filter'"
    done

    FILE_LIST=$(eval ls -1 $(dirname $CUR) $FC | sort | xargs)
    for FILE in $FILE_LIST
    do
        print "$SUBMENU<a href=\"$(basename $FILE)\">"
        print "$(basename $FILE | sed -e 's/(.\+)\.[A-Za-z0-9]\+/\1/')</a> \n"
    done

}

build_page () {
    # clear out vars
    PAGE=""
    FOOTER=""

    build_header
    build_submenu
    
    print $($MDPARSER $(basename $1))

    build_footer

}

# source config file and check valid targets and source dirs
. ./$CONF_FILE
if [ -z ${SRC_DIR} ]; then
    usage
fi

if [ -z ${TARGET} ]; then
    TARGET="$(pwd)/$(basename ${SRC_DIR}).build"
fi

# copy over target dir
cp -r ${SRC_DIR} ${TARGET}
cd ${TARGET}

# here's where we need to load in the list of files
# and convert md->html

